//! `writer build-lexicon` — extract canon lexicon from corpus.
//!
//! Builds a deterministic, no-ML lexicon of named entities and high-PMI
//! topic terms from the author's corpus. The lexicon is used by
//! `writer eval-style` to detect canon leakage in generated text.
//!
//! Strategy:
//! 1. Extract capitalized multi-word phrases (named entities)
//! 2. Compute PMI for single words against a general English baseline
//! 3. Filter by minimum count and score
//! 4. Write to `canon_lexicon.txt` in the profile directory
use std::collections::HashMap;

use serde::Serialize;

use writer_cli::corpus::sample::Sample;

use crate::config;
use crate::error::AppError;
use crate::output::{self, Ctx};

#[derive(Serialize)]
struct LexiconResult {
    profile: String,
    terms: usize,
    named_entities: usize,
    high_pmi_words: usize,
    path: String,
}

/// Common English words that should never appear in the canon lexicon.
/// These are too frequent in general text to be meaningful.
const STOPWORDS: &[&str] = &[
    "the", "a", "an", "is", "was", "were", "be", "been", "being", "have", "has", "had",
    "do", "does", "did", "will", "would", "could", "should", "may", "might", "shall",
    "can", "need", "dare", "ought", "used", "to", "of", "in", "for", "on", "with", "at",
    "by", "from", "as", "into", "through", "during", "before", "after", "above", "below",
    "between", "out", "off", "over", "under", "again", "further", "then", "once", "here",
    "there", "when", "where", "why", "how", "all", "both", "each", "few", "more", "most",
    "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than",
    "too", "very", "just", "because", "but", "and", "or", "if", "while", "that", "this",
    "these", "those", "it", "its", "he", "she", "they", "them", "his", "her", "their",
    "what", "which", "who", "whom", "whose", "we", "you", "your", "my", "our", "me",
    "him", "us", "i", "about", "up", "also", "said", "one", "two", "even", "much",
    "many", "well", "back", "still", "going", "really", "something", "nothing",
    "everything", "anything", "thing", "things", "like", "know", "think", "make",
    "take", "come", "go", "see", "look", "want", "give", "get", "say", "tell",
    "new", "good", "first", "last", "long", "great", "little", "right", "old",
    "big", "high", "small", "large", "next", "young", "important", "few", "public",
    "bad", "man", "woman", "time", "year", "people", "way", "day", "world", "life",
    "hand", "part", "place", "case", "week", "company", "system", "program", "question",
    "work", "government", "number", "night", "point", "home", "water", "room",
];

pub fn run(
    ctx: Ctx,
    profile: Option<String>,
    min_count: usize,
    max_terms: usize,
) -> Result<(), AppError> {
    let cfg = config::load()?;
    let profile_name = profile.unwrap_or_else(|| cfg.active_profile.clone());
    let profile_dir = config::profiles_dir().join(&profile_name);
    let corpus_path = profile_dir.join("samples/corpus.jsonl");

    if !corpus_path.exists() {
        return Err(AppError::Config(format!(
            "No corpus found for profile '{}'. Run: writer learn <files>",
            profile_name
        )));
    }

    let content = std::fs::read_to_string(&corpus_path)?;
    let samples: Vec<Sample> = content
        .lines()
        .filter_map(|line| serde_json::from_str(line).ok())
        .collect();

    if samples.is_empty() {
        return Err(AppError::InvalidInput(
            "Corpus is empty".to_string(),
        ));
    }

    let full_text: String = samples.iter().map(|s| s.content.as_str()).collect::<Vec<_>>().join("\n\n");

    // Extract named entities (capitalized multi-word sequences)
    let named_entities = extract_named_entities(&full_text, min_count);

    // Extract high-PMI single words
    let high_pmi = extract_high_pmi_words(&full_text, min_count);

    // Merge and deduplicate
    let mut all_terms: Vec<String> = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for (term, _count) in &named_entities {
        let lower = term.to_lowercase();
        if seen.insert(lower.clone()) {
            all_terms.push(lower);
        }
    }

    for (word, _pmi) in &high_pmi {
        let lower = word.to_lowercase();
        if seen.insert(lower.clone()) {
            all_terms.push(lower);
        }
    }

    all_terms.truncate(max_terms);

    // Write lexicon
    let lexicon_path = profile_dir.join("canon_lexicon.txt");
    let lexicon_content = format!(
        "# Canon lexicon for profile '{}'\n# Auto-generated by `writer build-lexicon`\n# {} named entities + {} high-PMI words\n# Edit to add/remove terms; lines starting with # are ignored\n\n{}\n",
        profile_name,
        named_entities.len().min(max_terms),
        high_pmi.len().min(max_terms.saturating_sub(named_entities.len())),
        all_terms.join("\n"),
    );
    std::fs::write(&lexicon_path, &lexicon_content)?;

    let result = LexiconResult {
        profile: profile_name,
        terms: all_terms.len(),
        named_entities: named_entities.len(),
        high_pmi_words: high_pmi.len(),
        path: lexicon_path.display().to_string(),
    };

    output::print_success_or(ctx, &result, |r| {
        use owo_colors::OwoColorize;
        println!(
            "{} Built canon lexicon: {} terms ({} entities + {} PMI words)",
            "+".green(),
            r.terms,
            r.named_entities,
            r.high_pmi_words,
        );
        println!("  path: {}", r.path.dimmed());
        println!("\n  Edit {} to refine.", "canon_lexicon.txt".bold());
    });

    Ok(())
}

/// Extract capitalized multi-word phrases that appear at least `min_count` times.
/// These are likely named entities: character names, place names, etc.
fn extract_named_entities(text: &str, min_count: usize) -> Vec<(String, usize)> {
    let mut phrases: HashMap<String, usize> = HashMap::new();

    // Simple heuristic: look for sequences of 2-4 capitalized words
    let words: Vec<&str> = text.split_whitespace().collect();

    for window_size in [2, 3, 4] {
        for window in words.windows(window_size) {
            let all_caps = window.iter().all(|w| {
                let clean = w.trim_matches(|c: char| !c.is_alphanumeric());
                !clean.is_empty() && clean.chars().next().is_some_and(|c| c.is_uppercase())
            });

            if all_caps {
                let phrase: String = window
                    .iter()
                    .map(|w| w.trim_matches(|c: char| !c.is_alphanumeric()))
                    .collect::<Vec<_>>()
                    .join(" ");

                if phrase.len() >= 3 {
                    *phrases.entry(phrase).or_insert(0) += 1;
                }
            }
        }
    }

    // Also find single capitalized words that aren't sentence starters
    // (heuristic: preceded by a non-period character)
    for (i, word) in words.iter().enumerate() {
        let clean = word.trim_matches(|c: char| !c.is_alphanumeric());
        if clean.is_empty() || clean.len() < 3 {
            continue;
        }

        let is_capitalized = clean.chars().next().is_some_and(|c| c.is_uppercase());
        if !is_capitalized {
            continue;
        }

        // Skip if it's likely a sentence starter
        if i == 0 {
            continue;
        }
        let prev = words[i - 1];
        let is_sentence_start = prev.ends_with('.') || prev.ends_with('!') || prev.ends_with('?');
        if is_sentence_start {
            continue;
        }

        // Skip common English words that happen to be at the start
        if STOPWORDS.contains(&clean.to_lowercase().as_str()) {
            continue;
        }

        *phrases.entry(clean.to_string()).or_insert(0) += 1;
    }

    let mut result: Vec<(String, usize)> = phrases
        .into_iter()
        .filter(|(_, count)| *count >= min_count)
        .collect();

    result.sort_by(|a, b| b.1.cmp(&a.1));
    result
}

/// Extract words with high corpus-specificity via simplified PMI.
/// Words that appear frequently in the corpus but are not common English words
/// are likely topic-specific and indicate canon content.
fn extract_high_pmi_words(text: &str, min_count: usize) -> Vec<(String, f64)> {
    let stopwords: std::collections::HashSet<&str> = STOPWORDS.iter().copied().collect();

    let mut word_counts: HashMap<String, usize> = HashMap::new();
    let total_words = text.split_whitespace().count();

    for word in text.split_whitespace() {
        let clean: String = word
            .chars()
            .filter(|c| c.is_alphanumeric() || *c == '\'')
            .collect::<String>()
            .to_lowercase();

        if clean.len() < 3 || stopwords.contains(clean.as_str()) {
            continue;
        }

        // Skip purely numeric tokens
        if clean.chars().all(|c| c.is_numeric()) {
            continue;
        }

        *word_counts.entry(clean).or_insert(0) += 1;
    }

    // Score by frequency relative to corpus size — higher frequency = more distinctive
    // (In a proper implementation we'd compare against a background corpus,
    // but for now high absolute frequency in a small author corpus is a good signal)
    let mut scored: Vec<(String, f64)> = word_counts
        .into_iter()
        .filter(|(_, count)| *count >= min_count)
        .map(|(word, count)| {
            let freq = count as f64 / total_words as f64;
            // Log-frequency as a proxy for distinctiveness
            let score = (freq * 10000.0).ln().max(0.0);
            (word, score)
        })
        .filter(|(_, score)| *score > 0.5) // Minimum distinctiveness threshold
        .collect();

    scored.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    scored
}
